### PR TITLE
setup manifest v3 for chrome

### PR DESCRIPTION
**Pull request by creesch**
Tested and it seems to work, but this should not be merged before #631 and before ratelimiting is rewriten to not use timers (or is removed as reddit clearly doesn't enforce it).

### CODE REVIEW

**Comment by creesch** [comment]
image

**Review by eritbh — COMMENTED** [review]
If we're doing separate Chromium and Firefox manifest files, we should probably get rid of the platform-specific `transform` hook in the rollup config and just include those changes in each file

**Comment by creesch** [comment]
> If we're doing separate Chromium and Firefox manifest files, we should probably get rid of the platform-specific `transform` hook in the rollup config and just include those changes in each file

Yeah true, I'll make the change.

**Review by eritbh — APPROVED** [review]

**Comment by eritbh** [comment]
Will this close #555 (the main mv3 tracking issue) or do we plan to keep that open after the fact to address other things?

> this should not be merged... before ratelimiting is rewriten to not use timers (or is removed as reddit clearly doesn't enforce it).

#637 removes ratelimiting entirely and will un-block this PR.

**Comment by creesch** [comment]
> Will this close https://github.com/toolbox-team/reddit-moderator-toolbox/issues/555 (the main mv3 tracking issue) or do we plan to keep that open after the fact to address other things? 

Let's keep it for a little bit

**Pull request merged**
