### PR TITLE
Use ratelimit handler for OAuth requests

### LINKED ISSUE #248: Handle ratelimiting consistently
The only real ratelimiting code toolbox actually has is in [TBCore.forEachChunkedRateLimit](), which from what I can tell basically says "here's a function that'll make x API calls, run it y times as fast as you can but don't let the `Ratelimit-Remaining` header dip below 20 and if it does stop everything for six minutes". It was added [back in 2015](https://github.com/toolbox-team/reddit-moderator-toolbox/commit/92298a628feb2aca4bf76c9435a7d1f87e28e99a#diff-c9da5bc7882bb894de2a63a2aaede53aR1027-R1098) and hasn't significantly changed since.

This system provides only very weak protection, relies on tons of assumptions, is written in a very messy and hard-to-understand way, provides no protection for API calls that are made outside this function, and [may just not work as intended at all](https://discordapp.com/channels/535490452066009090/535490452066009093/685253706178101312) when a large amount of requests are required (e.g. usernote pruning by activity).

Anyway enough ranting about that. Ratelimiting should be handled in the background page, by the request handler, by actually reading the ratelimit headers for every request and queueing requests to be sent if more stack up than can be handled in the current ratelimit bucket. Care should be taken to ensure that `ratelimit-reset` headers are interpreted properly so we don't end up waiting longer for ratelimits than we have to.

This system will protect *all* requests from ratelimit-related failure and will obviate `TBCore.forEachChunkedRateLimit`. It can then be removed and replaced by simple `for` loops, and we can make sure that appropriate loading indicators are displayed for all tasks that may take a long time to complete due to frequent limiting.

### PR DESCRIPTION
**Pull request by eritbh**
Fixes #248. Adds a ratelimit handler class to the background page which is used for OAuth requests. The handler supports parallel requests up to the size of the current ratelimit bucket, so this should theoretically improve performance for some mass actions (which were limited to 20 requests per batch). I'll try to do a performance comparison in a bit.

(Edit: I just noticed that some `old.reddit.com` requests are receiving ratelimit responses as well. I'll look into this further and adapt this.) ~~As only `oauth.reddit.com` responds with ratelimit headers~~, this PR converts the methods that were previously controlled by `forEachChunkedRateLimit` to use OAuth rather than modhash authentication. The `forEachChunkedRateLimit` function itself is replaced with a `Promise.all()` structure that queues all requests at once and waits for all requests to complete before calling the completion handler.

This is in a functional state, but does not yet include a "you are being ratelimited" notification.

### CODE REVIEW

**Comment by creesch** [comment]
> (Edit: I just noticed that some old.reddit.com requests are receiving ratelimit responses as well. I'll look into this further and adapt this

Afaik all of them do or should in any case (maybe reddit did mess it up somewhere), otherwise we wouldn't have been able to have our current ratelimiting system in place.

**Comment by Geo1088** [comment]
On further inspection it seems like they only send them for `.json` requests. Stuff like fetching unread messages returns ratelimits, but hitting `/api/remove` doesn't actually appear to in my testing. Which means I'm really not sure how the current system functions at all for comment nuking.

Requests against non-JSON routes do seem to impact the ratelimits, they just don't contain headers. Since I account for that in the ratelimiter code, I think we should be fine to just set up one ratelimiter for OAuth requests and another for non-OAuth. I'll do that today.

**Comment by creesch** [comment]
Doesn't the current system proactively check for the ratelimit before doing bulk requests? 

Still odd that not all requests contain that information, I rather not move too much things to oauth as we have had some scattered reports of oauth not working for all people (specifically on firefox).

**Comment by Geo1088** [comment]
Oh, right, that function sent a request to a wiki JSON page to get the ratelimit headers from there. That makes sense now.

If you'd rather not move bulk action processing to OAuth, I can revert those changes. It should be fine to let them use the existing ratelimiter without much trouble - it's designed in such a way that even if we don't get ratelimit information, it should handle itself smoothly, falling back to serial requests if it doesn't know how much ratelimit is remaining. I'll have to test whether old.reddit sends 429s if the limit is exceeded or if I need to do special retry handling there, but it shouldn't be a big deal.

**Comment by creesch** [comment]
If reddit let's us know properly that we are ratelimited when it happens I have no issue with a new method centered around that. Has been a while since I experimented with it though so I don't know if reddit does actually do that properly or just picked another random error code and throws in some html in the response as an extra fuck you.

**Comment by Geo1088** [comment]
This should be in a mergeable state now, but let's hold it until we're done with 5.5 bugfix updates.

**Pull request merged**
