### PR TITLE
Update repo meta files

### PR DESCRIPTION
**Pull request by eritbh**
Sprucing up our README and CONTRIBUTING documents a bit.

- [x] Remove some old stuff that I don't believe gets used anymore
  - [x] Travis badge, since we don't appear to use it anymore (@creesch might want to confirm everything that needs to be taken off of there is off of there, any secrets or other stuff)
  - [x] IRC badge (this I'm not actually positive about, we might want to keep it around? i'm just not in it anymore)
  - [x] Sauce Labs blurb? do we still use their stuff?
- [x] Reformat files to remove trailing spaces, use consistent header forms, etc.
- [x] Use consistent link style in README (all footnote-style links or all inline links, let's not mix them [except for images I guess])
- [x] Add readme badges for extension versions
  - [x] Chrome
  - [x] Firefox
  - [x] Edge (i forgot)

fixing the rest tomorrow

### CODE REVIEW

**Comment by creesch** [comment]
Looks good to me! We don't use travis anymore (We need to fix our doc generation to use github actions, I think I made an issue for that) so that is fine. 

> Sauce Labs blurb? do we still use their stuff?

Not really, it is required to use their stuff without paying but we never ended up implementing front-end e2e tests.


> Use consistent link style in README (all footnote-style links or all inline links, let's not mix them [except for images I guess])

I am not sure I follow what you mean but do what you like best and that will be the standard :D

**Comment by eritbh** [comment]
Right, the issue for fixing Travis doc generation was #570. Are we good to remove the IRC link as well or do you still hang out in there? Wanted to get confirmation on that too

**Comment by creesch** [comment]
Oh yeah, irc can go as well.

**Comment by eritbh** [comment]
Cool, this should be all set then!

**Pull request merged**
