### PR TITLE
fix(Modbar): don't count highlighted in count

### LINKED ISSUE #162: bug(Modbar): New Modmail count includes highlighted
Right now it includes highlighted, which will be added to the count with in progress, or new and will thus report twice. 

This is one modmail, not two
image

### PR DESCRIPTION
**Pull request by SpyTec**
fixes #162

### CODE REVIEW

**Comment by SpyTec** [comment]
Or maybe there's more to this issue. Is it possible that someone highlights and archives a modmail and it still exists shows up in count endpoint?

**Comment by creesch** [comment]
> Is it possible that someone highlights and archives a modmail and it still exists shows up in count endpoint?

Possibly, it is probably easier to just leave the count as it is.

**Comment by SpyTec** [comment]
If it is the case, then yes. No way we can figure out whether to remove highlighted or not - would be a different matter if highlighted was counted separately (#159) ;)

**Comment by creesch** [comment]
Checked it, seems to be okay.

**Pull request merged**
