### PR TITLE
fix(ModBar): Keep "Open in old Reddit" button synced with URL in new Reddit

### LINKED ISSUE #142: "open in old Reddit" button doesn't update its href when navigating different pages on new Reddit
The current code sets the `href` of the link once when the page loads, but since new reddit is a SPA that updates `window.location` without reloading the page, the button still points to the initial page unless the browser is reloaded manually.

Ideally we can still keep the button as a link, because that makes middle-clicking work, and instead just update the `href` when we get a page navigation event from the jsapi.

### PR DESCRIPTION
**Pull request by SpyTec**
fixes #142

### CODE REVIEW

**Comment by SpyTec** [comment]
Yeah something broke.

**Comment by SpyTec** [comment]
Synced with upstream

**Comment by creesch** [comment]
I forgot, did you still need to change something in this one?

**Comment by SpyTec** [comment]
Nope!

**Pull request merged**
